import { Manrope } from 'next/font/google';

import 'swiper/css';
import 'swiper/css/effect-creative';

import { LocaleLayout } from '@/features/language/processes/language.provider';

import Providers from '@/app/(initialize)/providers';
import './globals.css';
import { notFound } from 'next/navigation';
import { routing } from '@/features/language/hooks/lang';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }) {
    const { locale } = await params;
    const className = `${manrope.variable} antialiased min-h-screen max-w-screen`;

    // if (!routing.locales.includes(locale)) {
    //     notFound();
    // }
    return (
        <LocaleLayout
            params={{ locale }}
            htmlBodyProps={{
                className: className,
            }}
        >
            <Providers>{children}</Providers>
        </LocaleLayout>
    );
}
